version: 2

models:
  - name: stg_financials
    description: "Cleaned financial records with GloBE Income adjustments."
    columns:
      - name: entity_id
        description: "Primary key for subsidiaries"
        tests:
          - unique
          - not_null

      - name: globe_income
        description: "Adjusted profit base for Pillar Two"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              description: "Income must be positive for top-up tax calculation"

  - name: fct_top_up_tax
    description: "The final Pillar Two tax liability calculation engine."
    columns:
      - name: effective_tax_rate
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1 # ETR cannot be more than 100%
